# Generated by Django 3.2.18 on 2023-04-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0008_auto_20230428_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiile',
            name='dob',
            field=models.DateField(blank=True, help_text='date form:YYYY-MM-DD', null=True),
        ),
    ]
