# Generated by Django 3.2.18 on 2023-05-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0010_userblogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBlogPost',
        ),
    ]
