# Generated by Django 3.2.18 on 2023-05-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0011_delete_userblogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Published')], default='draft', max_length=10),
        ),
    ]
